# Generated by Django 5.1.7 on 2025-03-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apiclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=25)),
                ('course_name', models.CharField(max_length=20)),
                ('course_duration', models.IntegerField()),
                ('seats', models.IntegerField()),
            ],
        ),
    ]
